### PR TITLE
Literal optimization

### LINKED ISSUE #59: Implement literals optimization
This seems like a really useful optimization. When the regex contains a literal, we can skip over the text until the first letter is found (i.e: calling `memchr`). Nim's `re` `find` and `findAll` are at least an order of magnitud faster because of this.

It should likely be part of another package that implements fast multi-literal searching `foo|bar|baz`, using both `memchr` when there's one or two literals, and a DFA or Aho–Corasick algorithm. It should also support unicode (`memchr` should search the Rune's last byte).

Then nim-regex can find the literal position and then match backward and forward.

### PR DESCRIPTION
**Pull request by nitely**
fix #59

### CODE REVIEW

**Comment by nitely** [comment]
@thomastay @timotheecour good news, my regex literal optimization is 34x faster than `re` for the email regex, and about the same speed for the rest. It's not even the macro version, that one would be faster, but I don't think I'll implement it.

```
============================================================================
GlobalBenchmark                                 relative  time/iter  iters/s
============================================================================
GlobalBenchmark                                            294.86ps    3.39G
============================================================================
bench.nim                                       relative  time/iter  iters/s
============================================================================
re_email_find_all                                           24.19ms    41.33
email_find_all                                  3389.08%   713.91us    1.40K
re_uri_find_all                                             24.75ms    40.40
uri_find_all                                      92.92%    26.64ms    37.54
re_ip_find_all                                               6.41ms   156.06
ip_find_all                                      101.27%     6.33ms   158.04
runes                                                        5.99ms   167.04
dummy                                                        0.00fs      inf
```

^ I've some uncommitted code to get these numbers, where I just allocate "submatches" once.

**Comment by timotheecour** [comment]
can you explain a bit the table? what is re_email_find_all vs email_find_all ? is `re_` the std/re  and the other one is your pkg/regex ?

so pkg/regex would be 33x slower than std/re for `email_find_all` task and about same speed for `ip_find_all` task?

**Comment by nitely** [comment]
> is re_ the std/re and the other one is your pkg/regex ?

Yes.

> so pkg/regex would be 33x slower than std/re for email_find_all task and about same speed for ip_find_all task?

It's 33x faster and about the same speed for the other tests.

**Comment by timotheecour** [comment]
oh dang, i misread us for ms!
wow this is nice?

does a comparison against nre make sense?

**Comment by nitely** [comment]
> does a comparison against nre make sense?

I just checked, and the numbers are about the same.

**Pull request merged**
